name: Push to DockerHub audiosort taged
on:
  push:
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.6.0
      with:
        images: orbitalteapot/audiocollectionsorter 
        
    - name: Build and push Docker images for audiocollectionsorter
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: AudioSort_Dockerfile
