name: Docker Image CI
on:
  push:
    branches:    
      - main
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN_V2 }}
        
    - name: Docker Metadata action
      uses: docker/metadata-action@v4.6.0
      with:
        images: ghcr.io/${{ github.repository }}
        
    - name: Build and push Docker images for audiobookcollectionsorter
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: audiobookcollectionsorter:${{ github.ref_name }}
        file: AudioBookSort_Dockerfile
        
    - name: Build and push Docker images for audiocollectionsorter
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: audiocollectionsorter:${{ github.ref_name }}
        file: AudioBookSort_Dockerfile
