name: Push to DockerHub audiosort latest
on:
  push:
    branches:        
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Docker Metadata action
      uses: docker/metadata-action@v4.6.0
      with:
        images: orbitalteapot/audiocollectionsorter 
        
    - name: Build and push Docker images for audiocollectionsorter
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: orbitalteapot/audiocollectionsorter:latest
        labels: ${{ steps.meta.outputs.labels }}
        file: AudioSort_Dockerfile
