name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        # push: true
        tags: audiocollectionsorter
        github-token: ${{ secrets.GHCR_TOKEN }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
